import { Lato, Montserrat } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";

import Navbar from "@/components/global/Navbar";


const lato = Lato({ subsets: ["latin"], weight: ["300","400","700"], variable: '--font-lato' })
const montserrat = Montserrat({ subsets: ["latin"], weight: ["300","400","700"], variable: '--font-montserrant' })


export const metadata: Metadata = {
  title: "Sippy Solar Panels",
  description: "Generated by create next appEmpower Los Angeles residents to embrace solar energy through an easy-to-use web application that streamlines scheduling for free solar panel evaluations, supporting the city’s mission to combat global warming",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${montserrat.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
